@startuml

!include common/theme.iuml
!include common/furps.iuml

title Нефункциональные требования\nЦифровизация депозитного направления
header Банк «Стандарт»
footer Опубликовано %date("d MMM YYYY")

:
|= Инициатива | Цифровизация депозитного направления бизнеса |
|= Целевой Milestone | MVP |
|= Ключевые компоненты | Сайт, Интернет-Банк |
|= Изменения затронут | АБС, XLS, система колл-центра |
;

:
$header("Комментарий")
$Reliability("")
$reliability("все сервисы доступны 24/7", "требование бизнеса")
$reliability("все сервисы доступны в 99.9% случаев", "требование бизнеса")
$reliability("сервисы интернет-банка должны выдерживать новую нагрузку", "требование бизнеса")
$reliability("система должна быть устойчива к выходу ЦОД из строя", "требование бизнеса")
$reliability("гарантированная доставка заявок и ставок между системами", "архитектурное требование для финтеха")
$reliability("транзакционность при работе с когерентными данными", "архитектурное требование для финтеха")
$Performance("")
$performance("нагрузка на АБС минимальна", "требование бизнеса, не должна влиять на её работоспособность")
$Supportability("")
$supportability("максимальное переиспользование технологий банка (MySQL, Oracle)", "требование бизнеса")
$supportability("документирование всех новых систем и протоколов", "требование бизнеса")
$supportability("новые технологии должны быть совместимы существующими платформами", "требование бизнеса")
$supportability("внутри банка должна быть экспертиза по внедряемому стеку", "требование бизнеса, допустимо использовать Kafka ''на перспективу''")
$supportability("централизованная система мониторинга", "для обнаружения проблем и прогнозирования")
$supportability("централизованная система сбора логов", "для отладки и постмортем-анализа")
$Restrictions("")
$restrictions("отказ от доработок СМС-шлюза подрядчиком", "требование бизнеса")
$restrictions("исключительно вертикальное масштабирование АБС", "ограничение базы данных")
$restrictions("отказ от прямой интеграции интернет-банка с АБС", "монолиту и так плохо")
$restrictions("отказ от использования XLS для расчёта ставок", "архитектурное требование")
$restrictions("доступ к данным ставок для кредитного и депозитного отделов разграничен", "требование безопасности")
;

@enduml
