@startuml

!include common/theme.iuml
!include common/furps.iuml

title FURPS+\nТребования к цифровизации депозитного направления
header Банк «Стандарт»
footer Опубликовано %date("d MMM YYYY")

:
|= Инициатива | Цифровизация депозитного направления бизнеса |
|= Целевой Milestone | MVP |
|= Ключевые компоненты | Сайт, Интернет-Банк |
|= Изменения затронут | АБС, XLS, система колл-центра |
;

:
$header("Комментарий")
$Functionality("Сайт")
$functionality("отображает список доступных депозитов с актуальными ставками", "требование бизнеса")
$functionality("позволяет клиентам создавать заявки на депозиты, указав номер телефона и ФИО", "требование бизнеса")
$functionality("оперативно передаёт заявку в систему колл-центра", "архитектурное требование \n пока не ясно, насколько оперативно, но очевидно, \n что клиент не будет ждать бесконечно")
$functionality("должен шифровать трафик с чувствительной информацией", "требование бизнеса")
$Functionality("Интернет-банк")
$functionality("отображает список доступных депозитов", "требование бизнеса")
$functionality("отображает актуальную ставку", "требование бизнеса")
$functionality("отображает персонализированные ставки", "требование бизнеса")
$functionality("позволяет клиентам создавать заявки на депозиты, указав счёт и сумму", "требование бизнеса")
$functionality("подтверждает операцию на создание депозита с помощью СМС-кода", "требование бизнеса")
$functionality("должен шифровать трафик с чувствительной информацией", "требование бизнеса")
$Functionality("Бэк-офис")
$functionality("депозитный отдел может работать со ставками по депозитам", "требование бизнеса")
$functionality("кредитный отдел может работать со ставками по депозитам", "требование бизнеса")
$functionality("процесс расчёта ставки централизован и автоматизирован, не требует обмена по почте", "архитектурное требование")
$functionality("процесс согласования персональной ставки централизован и автоматизирован, \n не требует обмена по почте", "архитектурное требование")
$Usability("Сайт")
$usability("соответствует системе дизайна для приложений банка", "требование бизнеса")
$usability("содержит привычные цвета и элементы брендирования", "требование бизнеса")
$usability("адаптирован под популярные устройства", "мобильные, планшеты, компьютеры - без них никак")
$usability("соответствует современным практикам по интуитивности", "меньше звонков в Колл-Центр")
$usability("отображает актуальное состояние заявок", "меньше звонков в Колл-Центр")
$Usability("Интернет-Банк")
$usability("соответствует системе дизайна для приложений банка", "требование бизнеса")
$usability("содержит привычные цвета и элементы брендирования", "требование бизнеса")
$usability("адаптирован под популярные устройства", "мобильные, планшеты, компьютеры - без них никак")
$usability("соответствует современным практикам по интуитивности", "меньше звонков в Колл-Центр")
$usability("отображает актуальное состояние заявок", "меньше звонков в Колл-Центр")
$Reliability("")
$reliability("все сервисы доступны 24/7", "требование бизнеса")
$reliability("все сервисы доступны в 99.9% случаев", "требование бизнеса")
$reliability("сервисы интернет-банка должны выдерживать новую нагрузку", "требование бизнеса")
$reliability("система должна быть устойчива к выходу ЦОД из строя", "требование бизнеса")
$reliability("гарантированная доставка заявок и ставок между системами", "архитектурное требование для финтеха")
$reliability("транзакционность при работе с когерентными данными", "архитектурное требование для финтеха")
$Performance("")
$performance("нагрузка на АБС минимальна", "требование бизнеса, не должна влиять на её работоспособность")
$Performance("Сайт")
$performance("отклик интерфейса измеряется миллисекундами", "требование бизнеса")
$performance("система должна обеспечивать равномерное горизонтальное масштабирование", "требование бизнеса")
$performance("статические данные загружаются менее, чем за 0.1 секунды в локальной сети", "требование бизнеса, справочники сюда же")
$Performance("Интернет-Банк")
$performance("отклик интерфейса измеряется миллисекундами", "требование бизнеса")
$performance("система должна обеспечивать равномерное горизонтальное масштабирование", "требование бизнеса")
$performance("статические данные загружаются менее, чем за 0.1 секунды в локальной сети", "требование бизнеса, справочники сюда же")
$Supportability("")
$supportability("максимальное переиспользование технологий банка (MySQL, Oracle)", "требование бизнеса")
$supportability("документирование всех новых систем и протоколов", "требование бизнеса")
$supportability("новые технологии должны быть совместимы существующими платформами", "требование бизнеса")
$supportability("внутри банка должна быть экспертиза по внедряемому стеку", "требование бизнеса, допустимо использовать Kafka ''на перспективу''")
$supportability("централизованная система мониторинга", "для обнаружения проблем и прогнозирования")
$supportability("централизованная система сбора логов", "для отладки и постмортем-анализа")
$Restrictions("")
$restrictions("отказ от доработок СМС-шлюза подрядчиком", "требование бизнеса")
$restrictions("исключительно вертикальное масштабирование АБС", "ограничение базы данных")
$restrictions("отказ от прямой интеграции интернет-банка с АБС", "монолиту и так плохо")
$restrictions("отказ от использования XLS для расчёта ставок", "архитектурное требование")
$restrictions("доступ к данным ставок для кредитного и депозитного отделов разграничен", "требование безопасности")
;

@enduml
