@startuml

!include common/theme.iuml
!include common/usecase.iuml


title Use Cases\nЦифровизация депозитного направления
header Банк «Стандарт»
footer Опубликовано %date("d MMM YYYY")

!$use_cases = [
    {
        "name": "Создание заявки на депозит новым клиентом",
        "participants": [
            "Новый Клиент",
            "Веб-Сайт",
            "Оператор колл-центра"
        ],
        "steps": [
            "Сайт отображает депозиты новым клиентам (публично)",
            "На сайте Новый Клиент видит список доступных депозитов с актуальными ставками",
            "Новый Клиент подаёт заявку на депозит, оставив свой номер телефона и Ф.И.О.",
            "Сайт отправляет заявку на депозит в систему колл-центра по защищенному каналу связи",
            "Система колл-центра принимает заявку на депозит",
            "Оператор колл-центра видит заявку на депозит в системе колл-центра",
            "Оператор колл-центра связывается с клиентом и подтверждает заявку на депозит",
            "Заявка передаётся в АБС для дальнейшей обработки"
        ]
    },
    {
        "name": "Обработка заявки на депозит новым клиентом",
        "participants": [
            "Менеджер депозитов",
            "АБС"
        ],
        "steps": [
            "Заявка получена АБС из системы колл-центра",
            "Менеджер депозитов изучает заявку на депозит",
            "Менеджер депозитов рассчитывает ставку",
            "Менеджер депозитов дополняет заявку условиями и подтверждает ставку",
            "АБС сохраняет заявку",
            "АБС отправляет СМС Новому Клиенту с информацией о депозите и приглашение в офис банка"
        ]
    },
    {
        "name": "Открытие депозита новому клиенту",
        "participants": [
            "Новый Клиент",
            "Менеджер фронт-офиса",
            "Менеджер депозитов",
            "АБС"
        ],
        "steps": [
            "Заявка получена АБС из системы колл-центра",
            "Новый Клиент приходит в офис банка",
            "Менеджер фронт-офиса идентифицирует клиента",
            "Менеджер фронт-офиса подтверждает личные данные в заявке",
            "Менеджер депозитов видит подтверждение заявки в АБС",
            "Менеджер депозитов подтверждает открытие депозита",
            "АБС создаёт депозит",
            "АБС отправляет СМС клиенту с информацией о депозите",
            "Менеджер фронт-офиса проводит пополнение депозита через кассу",
            "Менеджер фронт-офиса убеждается, что клиент удовлетворён депозитом"
        ]
    },
    {
        "name": "Создание заявки на депозит старым клиентом",
        "participants": [
            "Старый клиент",
            "Интернет-Банк"
        ],
        "steps": [
            "Интернет-Банк отображает депозиты старым клиентам с актуальными ставками",
            "Интернет-Банк отображает персонализированные ставки для старых клиентов",
            "Старый клиент видит список доступных депозитов",
            "Старый клиент выбирает депозит и отправляет заявку на открытие депозита",
            "Интернет-Банк отправляет заявку на открытие депозита в АБС по защищенному каналу связи"
        ]
    },
    {
        "name": "Обработка заявки на депозит старым клиентом",
        "participants": [
            "Старый клиент",
            "Менеджер депозитов",
            "АБС"
        ],
        "steps": [
            "Менеджер депозитов изучает заявку на депозит в АБС",
            "Менеджер депозитов рассчитывает ставку",
            "Менеджер депозитов дополняет заявку условиями и подтверждает ставку",
            "АБС отправляет СМС клиенту для подтверждения открытия депозита",
            "Клиент подтверждает открытие депозита кодом из СМС в интернет-банке",
            "АБС создаёт депозит",
            "АБС отправляет СМС клиенту с информацией о депозите"
        ]
    }
]
$UseCases($use_cases=$use_cases)

@enduml