@startuml
package "Продажи и маркетинг" {
    [Продажи в сети отделений]
    [Продажи через колл-центр]
    [Digital-оповещения клиентов]
}
package "Поддержка операционных процессов" {
    [Обслуживание депозитных процессов]
    [Обслуживание кредитных процессов]
    [Управление договорами]
}
@enduml