@startuml

!include <C4/C4_Component>
!include common/c4-custom-rel.iuml
!include common/theme.iuml

skinparam nodesep 64
skinparam ranksep 64
skinparam style strictuml
skinparam NoteTextAlignment left
<style>
root{
    Margin: 32
}
ComponentDiagram {
    FontName: $FONT_NAME_LARGE
}
Arrow {
    LineColor: Gray
    LineThickness: 3
    FontStyle: bold
}
Interface {
    backgroundColor: $SYSTEM_BG_COLOR
    .ext {
        backgroundColor: $EXTERNAL_SYSTEM_BG_COLOR
    }
}
Legend {
    BackgroundColor: Transparent
    LineThickness: 0
}
Note {
    BackgroundColor: cornsilk
}
</style>

AddRelTag("interface", $lineThickness="8", $lineColor=$SYSTEM_BG_COLOR)
AddRelTag("interface-ext", $lineThickness="8", $lineColor=$EXTERNAL_SYSTEM_BG_COLOR)

title Диаграмма Компонентов\nМикросервис заявок
header Банк «Стандарт»
footer Опубликовано %date("d MMM YYYY")

Container(abs.core, "АБС\nСервер", "Delphi", "Монолит")

Container(sms_gateway, "СМС\nшлюз")
Container(website, "Веб-сайт", "PHP, React.js")
Container(internet_bank, "Интернет-банк", "ASP.NET, MVC 4.5")
System_Ext(call_center_platform, "Платформа для колл-центра", "//React.js, Java Spring, PostgreSQL//")

Container_Boundary(orders, "Микросервис\nзаявок") {
    Component(orders.core, "Микросервис\nзаявок", "PHP")
    Component(orders.abs_adapter, "Аадаптер протокола АБС", "PHP")
    Component(orders.ccp_adapter, "Аадаптер протокола Колл-центра", "PHP")
    Component(orders.memcache, "Кэш текущего состояния заявок", "Redis / memcached")
}

Rel_L(orders.core, orders.abs_adapter, "REST", "HTTPS")
Rel_R(orders.core, orders.ccp_adapter, "REST", "HTTPS")
Rel_U(orders.core, orders.memcache, "")

Rel_D(orders.ccp_adapter, call_center_platform, "REST", "HTTPS")
Rel_D(orders.abs_adapter, abs.core, "Ingress\nЗаявок")
Rel_D(orders.core, sms_gateway, "pub-sub")
Rel_U(website, orders.core, "REST", "HTTPS")
Rel_U(internet_bank, orders.core, "REST", "HTTPS")

@enduml


