@startuml
!include <C4/C4_Context>
!include common/theme.iuml

LAYOUT_WITH_LEGEND()

skinparam style strictuml
skinparam nodesep 64
skinparam NoteTextAlignment left
<style>
root{
    Margin: 32
}
ComponentDiagram {
    FontName: $FONT_NAME_LARGE
}
Arrow {
    LineColor: Gray
    LineThickness: 3
}
Legend {
    BackgroundColor: Transparent
    LineThickness: 0
}
Note {
    BackgroundColor: cornsilk
}
</style>

title Диаграмма Интеграции Приложений\nТекущая ситуация (as is)
header Банк «Стандарт»
footer Опубликовано %date("d MMM YYYY")

AddElementTag("bad", $borderThickness="4", $borderColor="#red")
AddRelTag("bad", $lineThickness="4", $lineColor="#red")
AddRelTag("new", $lineColor="#blue")

' ================================================================================
' Явно указанные в брифинге подразделения, системы и связи
' ================================================================================

' > **Управление обслуживанием депозитных продуктов.** Сюда относятся менеджеры бэк-офиса, которые специализируются на депозитах. Всего их 50 человек.
Person(back_office_deposit, "Бэк-офис\n(депозиты)", "50 человек")
' > **Управление обслуживанием кредитных продуктов.** Сюда относятся менеджеры бэк-офиса, которые специализируются на кредитах. Их тоже 50 человек.
Person(back_office_credit, "Бэк-офис\n(кредиты)", "50 человек")
' > Ещё внутри направления есть команда, которая занимается непосредственно АБС — автоматизированной банковской системой. Этот отдел состоит из 20 человек.
Person(it_department_abs, "Команда АБС", "20 человек")
' > - **Команда цифровой трансформации розничного бизнеса.** В ней 10 человек.
Person(digital_transformation_team, "Команда\nЦифровой\nТрансформации", "10 человек")
' > **Управление обслуживанием в сети отделений.** Сюда входят менеджеры фронт-офиса — сотрудники, которые работают в отделениях банка. У «Стандарта» 50 отделений в разных регионах. Там работают 500 человек.
Person(front_office, "Фронт-офис", "500 человек в 50 отделений")
' > **Кол-центр банка «Стандарт».** В банке работают 200 операторов.
Person(call_center_ops, "Колл-центр банка «Стандарт»", "200 операторов")
' > Он работает по готовым скриптам звонков, которые ему передают бизнес-представители банка.
Person(business_representatives, "Бизнес-представители")
' > Над интернет-банком работают две команды: внутри банка этим занимается 10 человек 
Person(it_department_int, "Управление IT для интернет-банка", "10 человек")

' > - **Сайт** — собственная разработка банка на PHP и React.js.
System(website, "Веб-сайт", "//PHP, React.js//")
' > - **Автоматизированная банковская система (АБС).** Интерфейс пользователей — это десктопный клиент на Delphi и СУБД на Oracle. Основная логика работы системы реализована процедурами на PL-SQL в СУБД. Система полностью разрабатывается внутри банка.
System(abs, "АБС", "//Delphi, Oracle//") {
    portin "Интерфейс\nбэк-офиса" as abs.backoffice.credit #lime
    portin "Интерфейс\nбэк-офиса" as abs.backoffice.deposit #lime
    portin "Доступ к коду" as abs.code #red
    portin "Заявки\nколл-центра" as abs.request #blue
    portin "СМС-канал" as abs.sms #blue
    portout "Интерфейс\nфроnt-офиса" as abs.frontoffice #lime
    portout " " #black
    portout "  " #black
    portout "   " #black
    portout "Доступ к БД" as abs.db #red
}
' > - **Интернет-банк.** Клиент-серверная система на веб-фреймворке ASP.NET MVC 4.5 на основе .NET Framework 4.5 и СУБД MS SQL.
System(internet_bank, "Интернет-банк", "//ASP.NET, MVC 4.5//")
' > - **СМС-шлюз телеком-оператора.** Его поддерживает IT-отдел банка, взаимодействуя с телеком-оператором.
System(sms_gateway, "СМС-шлюз")
' > - Сотрудники отдела кредитования вручную считают ставки в Excel-файле на основе ставки рефинансирования Центробанка
System(xls.credit, "Расчёт кредитных ставок" , "Excel", $tags="bad")
' > - Эти данные менеджер депозитов добавляет в Excel-файл и вычисляет на их основе ставку
' посчитаем, что это другой файл, т.к. есть
' > сотрудники депозитов и сотрудники кредитов не должны иметь доступа к данным друг друга по требованиям безопасности.
System(xls.deposit, "Расчёт депозитных ставок" , "Excel", $tags="bad")
' > - Сотрудник кредитования анализирует текущий уровень кредитного риска для банка в своём разделе АБС относительно этого клиента и передаёт данные в письме
' > - Он посылает её ответным письмом сотруднику фронт-офиса
System(mail, "Почтовый сервер", "")

' > На стороне подрядчика выделена команда сопровождения, которая поддерживает и дорабатывает систему. В ней работают пять человек.
Person_Ext(call_center_support, "Команда сопровождения колл-центра", "5 человек")
' > Ещё при необходимости компания может подключать партнёрский кол-центр.
' > - **Партнёрский кол-центр.** Команда партнёрского кол-центра насчитывает 100 человек.
Person_Ext(call_center_ext, "Партнёрский Колл-центр", "100 человек")
' > и ещё 10 человек работает на стороне подрядчика.
Person_Ext(it_department_ext, "Подрядчик IT для интернет-банка", "10 человек")
' > - Сотрудники отдела кредитования вручную считают ставки в Excel-файле на основе ставки рефинансирования Центробанка
System_Ext(central_bank, "Центробанк", "Рассылка банковской информации")

' > Также важно учитывать, что в качестве системы кол-центра банк использует не собственное решение, а платформу подрядчика.
' > - **Система кол-центра.** Это клиент-серверная система на платформе подрядчика, работает на технологиях подрядчика. Сама платформа предназначена для автоматизации CRM-решений, но банк использует только функционал кол-центра. У системы веб-интерфейс на React.js, бэкенд на Java Spring Boot и базы PostgreSQL. Архитектура микросервисная.
System_Ext(call_center_platform, "Платформа для колл-центра", "//React.js, Java Spring, PostgreSQL//")
' > - **Телеком-оператор** — внешний оператор по отправке СМС.
System_Ext(telecom_operator, "Телеком-оператор", "")
' > - **Система партнёрского кол-центра.** Это внешняя система. Партнёрский кол-центр и подрядчик, чью систему использует кол-центра банка, — разные компании.
System_Ext(call_center_ext_platform, "Система партнёрского колл-центра", "")

' > «Стандарт» — это небольшой банк. У него есть сайт и интернет-банк, но клиенты редко ими пользуются. Сайт умеет только показывать маркетинговую информацию, а функционал интернет-банка ограничивается проведением платежей и открытием текущих счетов (дебетовых карт).
Person_Ext(digital_visitor, "Клиенты\nмолодого\nвозраста")
' > Основная категория клиентов банка — Клиенты\nстаршего\nвозраста, которые предпочитают офлайн-обслуживание.
Person_Ext(senior_visitor, "Клиенты\nстаршего\nвозраста")

' > «Стандарт» — это небольшой банк. У него есть сайт и интернет-банк, но клиенты редко ими пользуются. Сайт умеет только показывать маркетинговую информацию, а функционал интернет-банка ограничивается проведением платежей и открытием текущих счетов (дебетовых карт).
Rel_D(website, digital_visitor, "маркетинг")
Rel_L(digital_visitor, internet_bank, "открытие счетов, проведение платежей")

' > Сотрудники в отделениях сейчас работают напрямую с автоматизированной банковской системой (АБС). Это основная система, где производится учёт операций по счетам и бухгалтерия.
Rel_U(front_office, abs.frontoffice, "Операции по счетам")
' > Менеджеры фронт-офисной системы работают с посетителями. Они несут ответственность за контактирование с людьми, маркетинг и продажи.
Rel_D(front_office, senior_visitor, "обслуживание клиентов, маркетинг, продажи")

' > Ещё внутри направления есть команда, которая занимается непосредственно АБС — автоматизированной банковской системой. Этот отдел состоит из 20 человек.
Rel_D(it_department_abs, abs.code, "разработка и поддержка")
' > Система развёрнута в инфраструктуре банка и полностью поддерживается подрядчиком. В команде АБС есть несколько специалистов с опытом в Java-стеке. Они могут периодически вносить изменения в систему самостоятельно по просьбе бизнеса, поскольку она имеет возможности для расширения.
Rel_U(it_department_abs, call_center_platform, "доработка и расширение")

' > Чтобы реализовать возможность проведения платежей и открытия текущих счетов, интернет-банк интегрировали с АБС — напрямую с её базой данных.
Rel_U(internet_bank, abs.db, "Проведение платежей\nоткрытие счетов", $tags="bad")

' > Сотрудники кол-центра принимают звонки через отдельную систему.
Rel_D(call_center_ops, call_center_platform, "приём звонков\nсоздание заявок")

' > На стороне подрядчика выделена команда сопровождения, которая поддерживает и дорабатывает систему. В ней работают пять человек.
Rel_L(call_center_support, call_center_platform, "поддержка и доработка")

' > Он работает по готовым скриптам звонков, которые ему передают бизнес-представители банка.
Rel_R(business_representatives, call_center_ext, "сценарии обзвона")

' > и ещё 10 человек работает на стороне подрядчика.
Rel_U(it_department_ext, internet_bank, "разработка и поддержка")

' > Над интернет-банком работают две команды: внутри банка этим занимается 10 человек 
Rel_D(it_department_int, internet_bank, "разработка и поддержка")

' > - **СМС-шлюз телеком-оператора.** Его поддерживает IT-отдел банка, взаимодействуя с телеком-оператором.
Rel_R(sms_gateway, telecom_operator, "передача данных")
Rel_U(it_department_int, sms_gateway, "разработка и поддержка")
Rel_U(it_department_int, telecom_operator, "согласование работ по шлюзу")

' > Сотрудники отдела кредитования вручную считают ставки в Excel-файле на основе ставки рефинансирования Центробанка
Rel_U(back_office_credit, xls.credit, "расчёт ставок", $tags="bad")

' > - Ставка обновляется ежедневно — эти показатели передаются в бэк-офис каждый день по почте Excel-файлом
Rel_R(central_bank, back_office_credit, "ставка рефинансирования", "Excel-файл")

' > 2. **Процесс с предварительным звонком в кол-центр:**
' >   - Если до своего визита клиент позвонил в кол-центр, чтобы уточнить детали открытия депозита, то сотрудник кол-центра заводит обращение в своей системе
' >   - Обращение передаётся в АБС
Rel_D(call_center_platform, abs.request, "передача заявок")

' > - **СМС-шлюз телеком-оператора.** Его поддерживает IT-отдел банка, взаимодействуя с телеком-оператором.
' - После этого АБС отправляет СМС-оповещение клиенту о том, что он может получить депозит под указанную ставку, — для этого надо прийти в отделение
Rel_R(abs.sms, sms_gateway, "СМС-оповещение")


' - Если у клиента достаточно много денег на счетах, ему могут согласовать специальные ставки
' - Чтобы их определить, сотрудники бэк-офиса обращаются в отдел кредитования
Rel_R(back_office_credit, back_office_deposit, "согласование ставок", "email", $tags="bad")

' - Эти данные менеджер депозитов добавляет в Excel-файл и вычисляет на их основе ставку
Rel_U(back_office_deposit, xls.deposit, "расчёт ставок", $tags="bad")

' - Если клиент приходит в отделение без предварительного звонка, то его заявку нельзя обработать заранее
' - В этом случае, чтобы озвучить клиенту ставку депозита, сотрудник отделения пишет письмо сотруднику бэк-офиса
Rel_U(front_office, mail, "запрос и\nполучение\nставок", "email", $tags="bad")
Rel_D(back_office_credit, mail, "получение\nзапросов", "email", $tags="bad")

' - Он посылает её ответным письмом сотруднику фронт-офиса
Rel_D(back_office_deposit, mail, "отправка\nставок", "email", $tags="bad")

' > Менеджеры бэк-офиса отвечают за деятельность компании на финансовых рынках и управление активами и пассивами банка. Они поддерживают внутренние бизнес-процессы, которые не видны клиентам.
' > Сейчас клиент может открыть депозитные и накопительные счета только в отделении банка. При этом задействованы и фронт-офис, и бэк-офис.
' > - Сотрудники бэк-офиса отдельно обрабатывают заявки из кол-центра в АБС, чтобы определить ставки для таких клиентов заранее
Rel_D(back_office_deposit, abs.backoffice.deposit, "работа с депозитами\nи заявками от КЦ")
' > - Сотрудник кредитования анализирует текущий уровень кредитного риска для банка в своём разделе АБС относительно этого клиента и передаёт данные в письме
Rel_R(back_office_credit, abs.backoffice.credit, "работа с кредитами")

' ================================================================================
' Не указанные напрямую в брифинге связи
' ================================================================================

' > - **Сайт** — собственная разработка банка на PHP и React.js.
' но не ясно, кем и как он был разработан, считаем, что департамент it
Rel_D(it_department_int, website, "разработка и поддержка")

' > - **Партнёрский кол-центр.** Команда партнёрского кол-центра насчитывает 100 человек.
' > - **Система партнёрского кол-центра.** Это внешняя система. Партнёрский кол-центр и подрядчик, чью систему использует кол-центра банка, — разные компании.
' Не указано явно, но достаточно очевидно, что партнерский кол-центр пользуется своей системой, скорее всего - для приёма звонков.
Rel_R(call_center_ext, call_center_ext_platform, "приём звонков")

' > Ещё при необходимости компания может подключать партнёрский кол-центр.
' Как и кем эта необходимость определяется - не указано.
' Можно предположить, что колл-центры выполняют по сути одну и ту же работу,
' следовательно партнёрский колл-центр - это "расширение мощностей" колл-центра банка
' на случай каких-нибудь промо-акций или других специальных случаев приводящих к большему количеству звонков.
' Для простоты картины посчитаем, что функцию масштабирования выполняют те же представители,
' что передают скрипты звонков. Возможно даже скрипты у партнёрского колл-центра будут
' более специализированными в зависимости от ситуации в штатном колл-центре.
Rel_D(business_representatives, call_center_platform, "анализ нагрузки")

' > - **Команда цифровой трансформации розничного бизнеса.** В ней 10 человек.
' Было бы странно, если бы эта команда уже была в банке на момент брифинга.
' Поэтому текущих связей с системами банка у ней нет.
' > Компания планирует развивать сайт и интернет-банк, чтобы предоставлять больше продуктов онлайн. Здесь две ключевые задачи.
' Покажем будущие связи, этой команде точно предстоит взаимодействовать с it-системами банка.
Rel_D(digital_transformation_team, website, "развитие", $tags="new")
Rel_D(digital_transformation_team, internet_bank, "развитие", $tags="new")
Rel_L(digital_transformation_team, abs, "развитие", $tags="new")
Rel_R(digital_transformation_team, it_department_int, "совместная\nработа", $tags="new")
Rel_U(digital_transformation_team, it_department_abs, "совместная\nработа", $tags="new")

' немного поможем plantuml с расположением стрелочек
Lay_R(mail, abs)
Lay_R(call_center_ops, business_representatives)

' Замечания по диаграмме
note as note.xls
=== Использование Excel для расчёта ставок не надёжно и не безопасно:
* Формат не подразумевает отслеживание истории изменений
* Не существует аудита использования
* Файлы легко скопировать или дать доступ лицам, которым он не должен быть виден
* Копирование ячеек может утекать формулы и названия листов наружу
* Алгоритм расчёта достаточно просто реверс-инжинирить
* Формат "файл" провоцирует пользователей совершать ошибки даже не преднамеренно
endnote
note.xls .d. xls.deposit
note.xls .d. xls.credit

note as note.mail
Сам по себе почтовый сервер проблемы не представляет.
Но передача данных через письма может быть не безопасна и очень медленна.
endnote
note.mail .r. mail

note as note.internet_bank
=== Подключение напрямую к БД АБС черевато проблемами:
* Открывать прямой доступ к БД АБС для систем вне АБС не безопасно
* АБС и Интернет-Банк могут пытаться внести противоречивые данные
* АБС и Интернет-Банк могут иметь разное состояние (в АБС могут быть кеши)
* Интернет-Банк открыт во внешний мир, есть риск SQL Injection прямо в БД АБС
endnote
note.internet_bank .u. internet_bank
' да, это очень странный хак для выравнивания, но АБС большая
Lay_D(abs.db, note.internet_bank)

' легенда с цветами связей
legend right
|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
|<$PERSON_BG_COLOR> Внутренний Агент |
|<$SYSTEM_BG_COLOR> Внутренняя Система |
|<$EXTERNAL_PERSON_BG_COLOR> Внешний Агент |
|<$EXTERNAL_SYSTEM_BG_COLOR> Внешняя Система |
| <color:red> ~~Проблемная Связь~~ |
| <color:blue> ~~Новая Связь~~ |
endlegend

@enduml
