@startsalt
!include common/theme.iuml
!include common/business-model-canvas.iuml

title Шаблон бизнес-модели\nБанк «Стандарт»
header Банк «Стандарт»
footer Опубликовано %date("d MMM YYYY")

!$KeyPartners = [
    ' Кто наши основные партнёры?
    ' Кто наши основные поставщики?
    ' Какие ресурсы мы от них получаем?
    ' Что они делают для нас?
    {"name" : "Партнёрский колл-центр", "desc" : "расширение штатного колл-центра"},
    {"name" : "IT Подрядчик колл-центра", "desc" : "сопровождение внутреннего колл-центра"},
    {"name" : "IT Подрядчик интернет-банка", "desc" : "сопровождение интернет-банка"},
    {"name" : "Провайдер ЦОД" , "desc" : "размещение интернет-банка"},
    {"name" : "Телеком-оператор", "desc" : "обслуживание СМС-оповещений"},
    {}
]
!$KeyActivities = [
    ' Какие действия придают ценность продукту?
    {"name" : "Сопровождение АБС", "desc" : "Необходимо для всех остальных действий"},
    {"name" : "Обслуживание онлайн", "desc" : "Важно для клиентов молодого возраста"},
    {"name" : "Обслуживание оффлайн", "desc" : "Важно для клиентов старшего возраста"},
    {"name" : "Обработка звонков", "desc" : ""},
    {"name" : "Обработка платежей", "desc" : ""},
    {"name" : "Открытие счетов", "desc" : ""},
    {"name" : "Управление счетами", "desc" : ""},
    {}
]
!$KeyResources = [
    ' Какие ресурсы мы используем для KeyActivities?
    ' Какие ресурсы нужны для придания значимости продукту?
    {"name" : "50 отделений", "desc" : "Персонал - 500 человек"},
    {"name" : "Колл-центр", "desc" : "Персонал - 200 человек"},
    {"name" : "АБС (Oracle, Delphi)", "desc" : "Внутренняя система"},
    {"name" : "IT инфраструктура", "desc" : "В отделениях и ЦОД"},
    {"name" : "Интернет-банк (ASP.NET, MS SQL)", "desc" : ""},
    {"name" : "Сайт (PHP, React.js)", "desc" : ""},
    {}
]
!$ValuePropositions = [
    ' В чём ценность продукта для клиента?
    ' Какую проблему клиента мы решаем?
    ' Какую потребность удовлетворяем?
    ' Какой продукт мы предлагаем клиенту?
    {"name" : "Привлекательные кредитные ставки", "desc" : ""},
    {"name" : "Оффлайн-обслуживание", "desc" : "Предпочтительно для клиентов старшего возраста"},
    {"name" : "Открытие карт онлайн", "desc" : ""},
    {"name" : "Проведение платежей онлайн", "desc" : ""},
    {"name" : "Открытие депозитов онлайн", "desc" : "Предпочтительно для клиентов молодого возраста", "new": true},
    {"name" : "Открытие накопительных счетов онлайн", "desc" : "Предпочтительно для клиентов молодого возраста", "new": true},
    {}
]
!$CustomerRelationships = [
    ' Какие взаимоотношения с нами ожидают наши клиенты?
    ' Индивидуальные или обезличенные?
    ' Интерактивные или автоматизированные?
    ' Оффлайн или удалённые?
    ' Краткосрочные или долгосрочные?
    {"name" : "Обслуживание в отделениях", "desc" : "Предпочтительно для клиентов старшего возраста"},
    {"name" : "Онлайн-заказ дебетовых карт", "desc" : "Предпочтительно для клиентов молодого возраста"},
    {"name" : "Обслуживание в интернет-банке", "desc" : "Предпочтительно для клиентов молодого возраста", "new": true},
    {"name" : "СМС-уведомления", "desc" : "Дополнительная услуга для счетов"},
    {}
]
!$DistributionChannels = [
    ' Через какие каналы мы будем поставлять продукт пользователям?
    ' Коммуникация? Физическая доставка? Услуги?
    ' Типичные каналы: прямой (тет-а-тет), посреднический (тет-а-тет, но делают партнёры), электронный (почта, сообщения), дистанционный (звонки, видеосвязь)
    {"name" : "50 отделений", "desc" : "Персональное обслуживание"},
    {"name" : "Колл-центр", "desc" : "Удаленное обслуживание"},
    {"name" : "Партнёрский Колл-центр", "desc" : "Удаленное обслуживание"},
    {"name" : "Интернет-банк", "desc" : "Онлайн-обслуживание", "new": true},
    {"name" : "Сайт", "desc" : "Маркетинговая информация"},
    {"name" : "СМС-уведомления", "desc" : "Маркетинговая информация"},
    {}
]
!$CustomerSegments = [
    ' Для кого мы делаем продукт значимым?
    ' Кто наш главный потребитель?
    ' Типичные сегменты: демографические, географические, поведенческие, потребностные, ценностные и т.д.
    {"name" : "Клиенты старшего возраста", "desc" : ""},
    {"name" : "Молодые клиенты", "desc" : "", "new": true},
    {}
]
!$CostStructure = [
    ' Каковы самые значительные затраты?
    ' Какой ресурс самый дорогой?
    ' Какая активность самая дорогая?
    ' Какие затраты наиболее волатильны?
    ' Какие затраты одномоментные?
    ' Какие затраты рекуррентные?
    {"name" : "Зарплаты сотрудников", "desc" : "Штат: отделения - 500, колл-центр - 200, бэк-офис - 100, it - 40"},
    {"name" : "Аренда/обслуживание помещений", "desc" : "50 отделений"},
    {"name" : "IT инфраструктура", "desc" : "Отделения, бэкенд банка"},
    {"name" : "IT подрядчики", "desc" : "Колл-центр и интернет-банк"},
    {"name" : "Услуги ЦОД", "desc" : "размещение интернет-банка"},
    {"name" : "Регулятивные расходы", "desc" : "Для краткости диаграммы все остальные стандартные расходы для банка входят в эту категорию"}
]
!$RevenueStreams = [
    ' За что именно в продукте платят потребители?
    ' За что ещё нам могут заплатить потребители?
    ' Как они оплачивают продукт?
    ' Сколько приносит каждый из источников в итоговый доход?
    ' Типичные источники дохода: продажи, сервисные сборы, подписки, аренда, лицензирование, услуги, реклама, комиссии.
    {"name" : "Процентные доходы от кредитов", "desc" : ""},
    {"name" : "Комиссии за переводы", "desc" : ""},
    {"name" : "Обслуживание счетов", "desc" : ""},
    {"name" : "Дополнительные услуги по счетам", "desc" : "Подписка на СМС-информирование, автоплатежи, доверительное управление"},
    {"name" : "Открытие дебетовых карт", "desc" : ""},
    {}
]

$BusinessModelCanvas( \
    $KeyPartners, \
    $KeyActivities, \
    $KeyResources, \
    $ValuePropositions, \
    $CustomerRelationships, \
    $DistributionChannels, \
    $CustomerSegments, \
    $CostStructure, \
    $RevenueStreams \
)


@endsalt

